[package]
name = "rrule"
description = "A pure Rust (partial) implementation of recurrence rules as defined in the iCalendar RFC."
license = "MIT"
version = "0.2.2"
authors = ["Fredrik Meringdal"]
edition = "2018"

keywords = ["calendar", "rrule", "ical"]
categories = ["Date and time"]

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.5.3"
once_cell = "1.4.1"
regex = "1.4.1"
