[package]
name = "rrule"
description = "Partial implementation of the ical specs"
license = "MIT"
version = "0.1.0"
authors = ["Fredrik Meringdal <fmeringdal@hotmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
once_cell = "1.4.1"
