[package]
name = "rrule-debugger"
version = "0.1.0"
edition = "2021"
authors = ["Ralph Bisschops <ralph.bisschops.dev@gmail.com>"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rrule = { path = "../rrule" }
chrono = "0.4.19"
chrono-tz = "0.6.1"
clap = { version = "3.2.5", features = ["derive"] }
rrule-afl-fuzz = { version = "0.1.0", path = "../rrule-afl-fuzz" }
log = "0.4.16"
yansi = "0.5.1"

[features]
default = []

no-validation-limits = ["rrule/no-validation-limits"]

by-easter = ["rrule/by-easter"]
